### ISSUE TITLE
[Suggestion] Airdrops like PUBG

### ISSUE THREAD

**Issue by 72stom** [Crazy-Crew/Crazy-Envoys#61]
For those who summon using Flare, 
Envoys appear around the place when summoned, 
Like an airdrop on Pubg. And emit a smoke particle or whatever

**Comment by Sparkaxd** [comment]
I have a suggestion on the leaderboard, I want placeholder texts in Turkish, can you help me?

**Comment by Sparkaxd** [comment]
![2022-05-06 (15)](https://user-images.githubusercontent.com/104910551/167167655-d7f7d421-ab3c-40c5-88c2-41af4e14bc88.png) 
I want the Turkish version

**Comment by badbones69** [comment]
CEv wasn't set up to be used like that but it could be done by moving the envoy center there and doing it that way. But it might make more sense for this to be another plugin since it has a different use than what CEv is currently going for unless it is added as a new feature that allows this as well. I'll leave this up if I ever get time to add this to it.

**Comment by RyderBelserion** [comment]
Added to our tracking board.
